# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

alias de='docker exec --e COLUMNS="$(tput cols)" -e LINES="$(tput lines)" -ti'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Command}}\t{{.Image}}"'
 
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit

# Enable vim mode
bindkey -v

# Aliases
alias rsync.exact="rsync -rtpogxv -P -l -H"
alias rsync.loose="rsync -zvru -P"
alias rgrep="grep -r"
alias vimconflicts='vim -p +/"<<<<<<<" $( git diff --name-only --diff-filter=U | uniq | xargs )'
alias -g g="| grep"
alias -g l="| less"
alias nnn="NNN_SHOW_HIDDEN=1 nnn -S"
alias df="pydf 2>/dev/null || df -h"
alias co="git checkout"
alias vim="nvim"
alias dad="python manage.py"

setopt EXTENDED_GLOB
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$PATH:/Users/gabrielescamilla/bin/flutter/bin"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
